language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - 3.6
matrix:
  fast_finish: true
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage -d htmlcov
  - pip install coveralls
  - coveralls
